name: Deploy backend to EC2

on:
  push:
    branches:
      - production
    paths:
      - "client/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Building files
        run: |
          cd client
          npm i pnpm -g
          pnpm i
          pnpm run build

      - name: Generate SSH key
        run: |
          echo "${{ secrets.PRIVATE_KEY }}" > ~/secret.pem
          chmod 600 ~/secret.pem

      - name: Copy build files
        run: scp -o StrictHostKeyChecking=accept-new -i "~/secret.pem" -r client/dist/ ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:react-notes/client/dist

      - name: SSH into EC2 instance and restarting client
        run: |
          ssh -i "~/secret.pem" ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} '
          pm2 restart note_client
          '
